## Functions in this file aim to cache the inverse of a matrix



## makeCacheMatrix creates a special matrix object able to cache the inverse of the input matrix
makeCacheMatrix <- function(x = matrix()) {
  invx <- NULL
  set <- function(y) {
    x <<- y
    invx <<- NULL #matrix has changed so reset the inverse
  }
  get <- function() x
  setinv <- function(inverse) invx <<- inverse 
  getinv <- function() invx
  list(set = set, 
       get = get,
       setinv = setinv,
       getinv = getinv)
  
}





## cacheSolve computes the inverse of a special "matrix" generated by makecacheMatrix
cacheSolve <- function(specX, ...) {
  
  ## Return a matrix that is the inverse of 'specX' 
  
  solved <- specX$getinv()
  if(!is.null(solved)) {
    message("getting cached inverse Matrix") # the inverse matrix is cached
    return(solved)
  }
  toSolve <- specX$get() # if we get here, the inverve is not cached so we get the matrix to invert
  solved <- solve(toSolve, ...) #the original matrix is always invertible, no test needed
  specX$setinv(solved) # set the setinv parameter of the special matrix
  solved
}
